"""Registered CPU-offline source benchmark adapters."""

from .base import (
    ACTION_POLICY_SCHEMA_VERSION,
    ADAPTER_REGISTRY,
    ASSET_CATALOG_SCHEMA_VERSION,
    EVALUATION_SCHEMA_VERSION,
    MEDIA_PLAN_SCHEMA_VERSION,
    OBSERVATION_SCHEMA_VERSION,
    PUBLIC_TASK_SCHEMA_VERSION,
    Adapter,
    AdapterClosedError,
    AdapterError,
    AdapterRegistrationError,
    AdapterSample,
    BaseAdapter,
    Choice,
    DataAbsenceError,
    DataUnavailableError,
    InvalidSubmissionError,
    MultipleChoiceOption,
    ParsedSubmission,
    SampleNotFoundError,
    create_adapter,
    discover_data_root,
    get_adapter_class,
    normalize_mcq_answer,
    normalize_multiple_choice,
    register_adapter,
    registered_adapters,
)
from .multiview import MMSIBenchAdapter, MindCubeAdapter
from .static import BOPASKAdapter, RoboSpatialHomeAdapter, ThreeDSRBenchAdapter
from .video import VSIBenchAdapter
from .integration import (
    AdapterPrivateEvaluatorGateway,
    build_offline_environment,
    materialize_typed_sample,
)


__all__ = [
    "ACTION_POLICY_SCHEMA_VERSION",
    "ADAPTER_REGISTRY",
    "ASSET_CATALOG_SCHEMA_VERSION",
    "EVALUATION_SCHEMA_VERSION",
    "MEDIA_PLAN_SCHEMA_VERSION",
    "OBSERVATION_SCHEMA_VERSION",
    "PUBLIC_TASK_SCHEMA_VERSION",
    "Adapter",
    "AdapterPrivateEvaluatorGateway",
    "AdapterClosedError",
    "AdapterError",
    "AdapterRegistrationError",
    "AdapterSample",
    "BaseAdapter",
    "Choice",
    "DataAbsenceError",
    "DataUnavailableError",
    "InvalidSubmissionError",
    "MMSIBenchAdapter",
    "MindCubeAdapter",
    "VSIBenchAdapter",
    "ThreeDSRBenchAdapter",
    "RoboSpatialHomeAdapter",
    "BOPASKAdapter",
    "MultipleChoiceOption",
    "ParsedSubmission",
    "SampleNotFoundError",
    "create_adapter",
    "build_offline_environment",
    "discover_data_root",
    "get_adapter_class",
    "normalize_mcq_answer",
    "normalize_multiple_choice",
    "materialize_typed_sample",
    "register_adapter",
    "registered_adapters",
]
