"""Embodied coding-agent harness package.

Top-level exports are intentionally lazy. OpenHands custom-tool registration
imports this package in a small SDK environment, so benchmark runtimes with
heavy simulator dependencies must only load when their symbols are requested.
"""

from __future__ import annotations

import importlib
from typing import Any

_EXPORT_MODULES = {
    "ALFWorldAgentRuntimeBackend": ".alfworld_agent_runtime",
    "ALFWorldRuntimeConfig": ".alfworld_agent_runtime",
    "AffordanceBatchReport": ".affordance_evaluation",
    "AffordanceEpisodeResult": ".affordance_evaluation",
    "AffordanceManifestRecord": ".affordance_manifest",
    "AffordanceSample": ".affordance_backend",
    "AffordanceTrajectoryLoader": ".affordance_backend",
    "AgentBenchmarkReport": ".api_agent_runner",
    "AgentTaskResult": ".api_agent_runner",
    "APICodingAgentRunner": ".api_agent_runner",
    "APIModelConfig": ".api_agent_runner",
    "BENCHMARK_CATALOG": ".benchmark_catalog",
    "BenchmarkDeclaration": ".catalog_schema",
    "CaseDeclaration": ".catalog_schema",
    "CatalogDeclaration": ".catalog_schema",
    "CatalogSchemaError": ".catalog_schema",
    "CONTROLLED_HARNESS_SCHEMA_VERSION": ".controlled_harness",
    "ControlledHarnessError": ".controlled_harness",
    "EXPECTED_BENCHMARK_IDS": ".catalog_schema",
    "EXPECTED_RUNTIME_TARGET_IDS": ".catalog_schema",
    "OFFICIAL_VERIFIER_MODES": ".catalog_schema",
    "SCHEMA_VERSION": ".catalog_schema",
    "SCOPES": ".catalog_schema",
    "ArenaPaths": ".paths",
    "ProjectPaths": ".paths",
    "PathConfigurationError": ".paths",
    "PROJECT_ROOT_ENV": ".paths",
    "ARTIFACT_ROOT_ENV": ".paths",
    "EXTERNAL_ROOT_ENV": ".paths",
    "CONFIG_ROOT_ENV": ".paths",
    "BENCHMARK_ROOT_ENV": ".paths",
    "CONTAINER_ROOT_ENV": ".paths",
    "BENCHMARK_FAMILY_REGISTRY": ".universal_interface",
    "Behavior1KAgentRuntimeBackend": ".behavior1k_agent_runtime",
    "Behavior1KRuntimeConfig": ".behavior1k_agent_runtime",
    "CALVINAgentRuntimeBackend": ".calvin_agent_runtime",
    "CALVINRuntimeConfig": ".calvin_agent_runtime",
    "CLIPortAgentRuntimeBackend": ".cliport_agent_runtime",
    "CLIPortRuntimeConfig": ".cliport_agent_runtime",
    "DEFAULT_OPENHANDS_CASE_ID": ".openhands_harness",
    "DEFAULT_SPATIALCLAW_REPO": ".spatialclaw_adapter",
    "EmbodiedBackend": ".backend",
    "EpisodeTrace": ".schemas",
    "EvaluationRunResult": ".evaluation",
    "EvaluationRunner": ".evaluation",
    "ExecutionResult": ".runner",
    "FakeBackend": ".fake_backend",
    "GroundingCandidate": ".maniskill_agent_runtime",
    "ManiSkillAgentRuntimeBackend": ".maniskill_agent_runtime",
    "ManiSkillRuntimeConfig": ".maniskill_agent_runtime",
    "MMSISpatialBackend": ".spatial_mmsi_adapter",
    "MMSI_BENCH_HF_DATASET": ".spatial_mmsi_adapter",
    "MMSI_BENCH_PARQUET": ".spatial_mmsi_adapter",
    "OPENHANDS_ARENA_CASE_ID_ENV": ".openhands_harness",
    "Observation": ".schemas",
    "OpenHandsHarnessConfig": ".openhands_harness",
    "OpenHandsRepresentativeCaseSpec": ".openhands_harness",
    "OpenHandsRuntimeProfileSpec": ".openhands_harness",
    "OpenHandsToolSpec": ".openhands_harness",
    "OpenHandsUniversalToolExecutor": ".openhands_harness",
    "OPERATION13_BENCHMARK_IDS": ".operation_campaign",
    "OPERATION13_TASK_COUNT": ".operation_campaign",
    "Operation13Campaign": ".operation_campaign",
    "Operation13Definition": ".operation_campaign",
    "EvaluationTask": ".full_evaluation",
    "PrimitiveCard": ".schemas",
    "PrimitiveResult": ".schemas",
    "RLBenchAgentRuntimeBackend": ".rlbench_agent_runtime",
    "RLBenchRuntimeConfig": ".rlbench_agent_runtime",
    "RoboCasa365AgentRuntimeBackend": ".robocasa365_agent_runtime",
    "RoboCasa365RuntimeConfig": ".robocasa365_agent_runtime",
    "RoboCasaAgentRuntimeBackend": ".robocasa_agent_runtime",
    "RoboCasaRuntimeConfig": ".robocasa_agent_runtime",
    "RoboDojoAgentRuntimeBackend": ".robodojo_agent_runtime",
    "RoboDojoPolicySkillConfig": ".robodojo_policy_skill",
    "RoboDojoRuntimeConfig": ".robodojo_agent_runtime",
    "RoboTwin2AgentRuntimeBackend": ".robotwin2_agent_runtime",
    "RoboTwin2RuntimeConfig": ".robotwin2_agent_runtime",
    "RoboWitsAgentRuntimeBackend": ".robowits_agent_runtime",
    "RoboWitsRuntimeConfig": ".robowits_agent_runtime",
    "SPATIALCLAW_UPSTREAM_COMMIT": ".spatialclaw_adapter",
    "ScienceWorldAgentRuntimeBackend": ".scienceworld_agent_runtime",
    "ScienceWorldRuntimeConfig": ".scienceworld_agent_runtime",
    "SkillHarnessBackend": ".affordance_backend",
    "SpatialBatchReport": ".spatial_evaluation",
    "SpatialClawAgentNativeBackend": ".spatialclaw_adapter",
    "SpatialClawRuntimeSmoke": ".spatialclaw_adapter",
    "SpatialDiagnosticBackend": ".spatial_backend",
    "SpatialDiagnosticLoader": ".spatial_backend",
    "SpatialEpisodeResult": ".spatial_evaluation",
    "SpatialSample": ".spatial_backend",
    "StatefulCodeRunner": ".runner",
    "TaskPackageChecker": ".task_package",
    "TaskPackageReport": ".task_package",
    "TaskSpec": ".schemas",
    "TraceEvent": ".schemas",
    "UNIVERSAL_ADAPTER_PROFILES": ".universal_interface",
    "UNIVERSAL_BUDGET_CONTRACT": ".universal_interface",
    "UNIVERSAL_INTERFACE_NAMES": ".universal_interface",
    "UniversalAdapterProfile": ".universal_interface",
    "UniversalEmbodiedBackend": ".universal_interface",
    "UniversalInterfaceSpec": ".universal_interface",
    "VSI_BENCH_HF_DATASET": ".spatial_vsi_adapter",
    "VerificationResult": ".schemas",
    "VimaBenchAgentRuntimeBackend": ".vimabench_agent_runtime",
    "VimaBenchRuntimeConfig": ".vimabench_agent_runtime",
    "VLABenchRuntime": ".vlabench_runtime",
    "VLABenchRuntimeError": ".vlabench_runtime",
    "W4BenchmarkBackend": ".w4_benchmark_backend",
    "W4EnvironmentSpec": ".w4_benchmark_backend",
    "W4SmokeTask": ".w4_benchmark_backend",
    "PukunAssetSpec": ".pukun_extension",
    "PukunEntry": ".pukun_extension",
    "PukunExtensionError": ".pukun_extension",
    "PukunValidationReport": ".pukun_extension",
    "build_pukun_extension_manifest": ".pukun_extension",
    "validate_pukun_extension": ".pukun_extension",
    "resolve_pukun_root": ".pukun_extension",
    "CAPX_REFERENCE_PRIMITIVES": ".pukun_extension",
    "CAPX_HANDLE_PREFIXES": ".pukun_extension",
    "DEFAULT_FIXTURE_CELLS": ".pukun_bridge",
    "PUKUN_BRIDGE_SCHEMA": ".pukun_bridge",
    "PUKUN_MULTI_TURN_SCHEMA": ".pukun_bridge",
    "PukunBridgeBackend": ".pukun_bridge",
    "PukunBridgeError": ".pukun_bridge",
    "PukunMultiTurnRunner": ".pukun_bridge",
    "PUKUN_DEPLOYMENT_SCHEMA": ".pukun_deployment",
    "deploy_pukun_assets": ".pukun_deployment",
    "aggregate_affordance_results": ".affordance_evaluation",
    "aggregate_spatial_results": ".spatial_evaluation",
    "bbox_iou": ".affordance_metrics",
    "bind_rgb_observation_to_action": ".robodojo_act_provenance",
    "benchmark_family_registry": ".universal_interface",
    "benchmark_catalog_manifest": ".benchmark_catalog",
    "get_project_paths": ".paths",
    "resolve_paths": ".paths",
    "resolve_project_root": ".paths",
    "resolve_under": ".paths",
    "load_json_yaml": ".catalog_schema",
    "validate_benchmark_document": ".catalog_schema",
    "validate_cases_document": ".catalog_schema",
    "validate_catalog": ".catalog_schema",
    "build_manifest_records_from_sea_afford": ".affordance_manifest",
    "build_openhands_controlled_harness_manifest": ".controlled_harness",
    "build_openhands_agent_server_config": ".openhands_harness",
    "build_openhands_case_manifest": ".openhands_harness",
    "build_openhands_mcp_config": ".openhands_harness",
    "build_openhands_representative_case_specs": ".openhands_harness",
    "build_openhands_runtime_profile_manifest": ".openhands_harness",
    "build_openhands_tool_specs": ".openhands_harness",
    "evaluate_region_submission": ".affordance_metrics",
    "inspect_robodojo_policy_skill": ".robodojo_policy_skill",
    "list_robodojo_policy_adapters": ".robodojo_policy_skill",
    "load_mmsi_bench_samples": ".spatial_mmsi_adapter",
    "load_mmsi_bench_samples_from_rows_api": ".spatial_mmsi_adapter",
    "load_spatialclaw_samples": ".spatialclaw_adapter",
    "load_vsi_bench_samples": ".spatial_vsi_adapter",
    "make_openhands_tool_executor_for_case": ".openhands_harness",
    "make_openhands_tool_executor_from_env": ".openhands_harness",
    "make_openhands_universal_backend_for_case": ".openhands_harness",
    "make_openhands_universal_backend_from_env": ".openhands_harness",
    "mmsi_record_to_spatial_sample": ".spatial_mmsi_adapter",
    "normalize_vsi_options": ".spatial_vsi_adapter",
    "openhands_case_id_from_env": ".openhands_harness",
    "openhands_benchmark_registry": ".openhands_harness",
    "openhands_adapter_profiles": ".universal_interface",
    "build_operation13_campaign": ".operation_campaign",
    "load_operation13_definition": ".operation_campaign",
    "validate_operation13_campaign_spec": ".operation_campaign",
    "validate_openhands_controlled_harness_manifest": ".controlled_harness",
    "verify_operation13_sealed_manifest": ".operation_campaign",
    "point_distance": ".affordance_metrics",
    "point_in_bbox": ".affordance_metrics",
    "run_affordance_scripted_report": ".affordance_evaluation",
    "run_evaluation": ".full_evaluation",
    "run_robodojo_policy_skill": ".robodojo_policy_skill",
    "run_spatial_scripted_report": ".spatial_evaluation",
    "scripted_affordance_policy": ".affordance_evaluation",
    "scripted_spatial_policy": ".spatial_evaluation",
    "spatial_sample_to_record": ".spatial_vsi_adapter",
    "spatialclaw_sample_to_spatial_sample": ".spatialclaw_adapter",
    "universal_adapter_profile": ".universal_interface",
    "universal_adapter_profiles": ".universal_interface",
    "universal_contract_manifest": ".universal_interface",
    "universal_interface_cards": ".universal_interface",
    "universal_interface_specs": ".universal_interface",
    "vsi_record_to_spatial_sample": ".spatial_vsi_adapter",
    "w4_environment_specs": ".w4_benchmark_backend",
    "write_agent_task_trace_artifacts": ".api_agent_runner",
    "write_mmsi_samples_jsonl": ".spatial_mmsi_adapter",
    "write_openhands_harness_artifacts": ".openhands_harness",
    "write_spatial_samples_jsonl": ".spatial_vsi_adapter",
}

__all__ = [
    "EmbodiedBackend",
    "AffordanceSample",
    "AgentBenchmarkReport",
    "AgentTaskResult",
    "APICodingAgentRunner",
    "APIModelConfig",
    "AffordanceBatchReport",
    "AffordanceEpisodeResult",
    "AffordanceManifestRecord",
    "AffordanceTrajectoryLoader",
    "BENCHMARK_CATALOG",
    "BenchmarkDeclaration",
    "CaseDeclaration",
    "CatalogDeclaration",
    "CatalogSchemaError",
    "CONTROLLED_HARNESS_SCHEMA_VERSION",
    "ControlledHarnessError",
    "EXPECTED_BENCHMARK_IDS",
    "EXPECTED_RUNTIME_TARGET_IDS",
    "OFFICIAL_VERIFIER_MODES",
    "SCHEMA_VERSION",
    "SCOPES",
    "ArenaPaths",
    "ProjectPaths",
    "PathConfigurationError",
    "PROJECT_ROOT_ENV",
    "ARTIFACT_ROOT_ENV",
    "EXTERNAL_ROOT_ENV",
    "CONFIG_ROOT_ENV",
    "BENCHMARK_ROOT_ENV",
    "CONTAINER_ROOT_ENV",
    "Behavior1KAgentRuntimeBackend",
    "Behavior1KRuntimeConfig",
    "EpisodeTrace",
    "EvaluationRunResult",
    "EvaluationRunner",
    "EvaluationTask",
    "ExecutionResult",
    "FakeBackend",
    "CALVINAgentRuntimeBackend",
    "CALVINRuntimeConfig",
    "CLIPortAgentRuntimeBackend",
    "CLIPortRuntimeConfig",
    "GroundingCandidate",
    "ManiSkillAgentRuntimeBackend",
    "ManiSkillRuntimeConfig",
    "MMSI_BENCH_HF_DATASET",
    "MMSI_BENCH_PARQUET",
    "MMSISpatialBackend",
    "Observation",
    "OPENHANDS_ARENA_CASE_ID_ENV",
    "OpenHandsHarnessConfig",
    "OpenHandsRepresentativeCaseSpec",
    "OpenHandsRuntimeProfileSpec",
    "OpenHandsToolSpec",
    "OpenHandsUniversalToolExecutor",
    "OPERATION13_BENCHMARK_IDS",
    "OPERATION13_TASK_COUNT",
    "Operation13Campaign",
    "Operation13Definition",
    "PrimitiveCard",
    "PrimitiveResult",
    "RLBenchAgentRuntimeBackend",
    "RLBenchRuntimeConfig",
    "RoboCasaAgentRuntimeBackend",
    "RoboCasa365AgentRuntimeBackend",
    "RoboCasa365RuntimeConfig",
    "RoboCasaRuntimeConfig",
    "RoboDojoAgentRuntimeBackend",
    "RoboDojoPolicySkillConfig",
    "RoboDojoRuntimeConfig",
    "RoboTwin2AgentRuntimeBackend",
    "RoboTwin2RuntimeConfig",
    "RoboWitsAgentRuntimeBackend",
    "RoboWitsRuntimeConfig",
    "ScienceWorldAgentRuntimeBackend",
    "ScienceWorldRuntimeConfig",
    "StatefulCodeRunner",
    "SkillHarnessBackend",
    "SpatialBatchReport",
    "DEFAULT_SPATIALCLAW_REPO",
    "SPATIALCLAW_UPSTREAM_COMMIT",
    "SpatialClawAgentNativeBackend",
    "SpatialClawRuntimeSmoke",
    "SpatialDiagnosticBackend",
    "SpatialDiagnosticLoader",
    "SpatialEpisodeResult",
    "SpatialSample",
    "TaskPackageChecker",
    "TaskPackageReport",
    "TaskSpec",
    "TraceEvent",
    "DEFAULT_OPENHANDS_CASE_ID",
    "BENCHMARK_FAMILY_REGISTRY",
    "UNIVERSAL_INTERFACE_NAMES",
    "UNIVERSAL_ADAPTER_PROFILES",
    "UniversalAdapterProfile",
    "UniversalEmbodiedBackend",
    "UniversalInterfaceSpec",
    "VSI_BENCH_HF_DATASET",
    "VerificationResult",
    "VimaBenchAgentRuntimeBackend",
    "VimaBenchRuntimeConfig",
    "VLABenchRuntime",
    "VLABenchRuntimeError",
    "W4BenchmarkBackend",
    "W4EnvironmentSpec",
    "W4SmokeTask",
    "CAPX_REFERENCE_PRIMITIVES",
    "CAPX_HANDLE_PREFIXES",
    "DEFAULT_FIXTURE_CELLS",
    "PUKUN_BRIDGE_SCHEMA",
    "PUKUN_MULTI_TURN_SCHEMA",
    "PukunAssetSpec",
    "PukunBridgeBackend",
    "PukunBridgeError",
    "PukunEntry",
    "PukunExtensionError",
    "PukunValidationReport",
    "PukunMultiTurnRunner",
    "PUKUN_DEPLOYMENT_SCHEMA",
    "deploy_pukun_assets",
    "build_pukun_extension_manifest",
    "validate_pukun_extension",
    "resolve_pukun_root",
    "aggregate_affordance_results",
    "aggregate_spatial_results",
    "bbox_iou",
    "bind_rgb_observation_to_action",
    "build_manifest_records_from_sea_afford",
    "build_openhands_agent_server_config",
    "build_openhands_controlled_harness_manifest",
    "build_openhands_case_manifest",
    "build_openhands_representative_case_specs",
    "build_openhands_runtime_profile_manifest",
    "build_openhands_mcp_config",
    "build_openhands_tool_specs",
    "evaluate_region_submission",
    "point_distance",
    "point_in_bbox",
    "inspect_robodojo_policy_skill",
    "list_robodojo_policy_adapters",
    "make_openhands_tool_executor_for_case",
    "make_openhands_tool_executor_from_env",
    "make_openhands_universal_backend_for_case",
    "make_openhands_universal_backend_from_env",
    "openhands_case_id_from_env",
    "benchmark_family_registry",
    "benchmark_catalog_manifest",
    "get_project_paths",
    "resolve_paths",
    "resolve_project_root",
    "resolve_under",
    "load_json_yaml",
    "validate_benchmark_document",
    "validate_cases_document",
    "validate_catalog",
    "openhands_benchmark_registry",
    "openhands_adapter_profiles",
    "build_operation13_campaign",
    "load_operation13_definition",
    "validate_operation13_campaign_spec",
    "validate_openhands_controlled_harness_manifest",
    "verify_operation13_sealed_manifest",
    "universal_adapter_profile",
    "universal_adapter_profiles",
    "universal_contract_manifest",
    "run_affordance_scripted_report",
    "run_evaluation",
    "run_robodojo_policy_skill",
    "run_spatial_scripted_report",
    "scripted_affordance_policy",
    "scripted_spatial_policy",
    "universal_interface_cards",
    "universal_interface_specs",
    "load_mmsi_bench_samples",
    "load_mmsi_bench_samples_from_rows_api",
    "load_spatialclaw_samples",
    "load_vsi_bench_samples",
    "mmsi_record_to_spatial_sample",
    "normalize_vsi_options",
    "spatial_sample_to_record",
    "spatialclaw_sample_to_spatial_sample",
    "vsi_record_to_spatial_sample",
    "w4_environment_specs",
    "write_mmsi_samples_jsonl",
    "write_agent_task_trace_artifacts",
    "write_openhands_harness_artifacts",
    "write_spatial_samples_jsonl",
]


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
