from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class PrimitiveCard:
    name: str
    signature: str
    canonical_family: str
    description: str
    arguments: dict[str, str]
    returns: str
    side_effect: str
    leakage_level: str
    limitations: list[str]
    backend_source: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


PRIMITIVE_CARDS = [
    PrimitiveCard("get_task_context", "get_task_context()", "CTX", "Return ALFRED task id, split, task type, goal text, public step-by-step language instructions, and public scene name.", {}, "dict", "none", "L1", ["Step-by-step language instructions are public ALFRED annotations, not expert actions. Does not expose expert plans, PDDL params, init action, low_actions, masks, raw traj path, or hidden metadata."], "official manifest public fields"),
    PrimitiveCard("list_actions", "list_actions()", "CTX", "List the exposed ALFRED visual primitive surface.", {}, "list[str]", "none", "L1", ["This is not the full AI2-THOR action set."], "harness facade"),
    PrimitiveCard("observe", "observe()", "PER", "Return current frame shape, agent pose, visible object summaries, and inventory.", {}, "dict", "none", "L1/L2", ["Does not return hidden objects, expert plan, or raw image bytes."], "ThorEnv.last_event metadata"),
    PrimitiveCard("get_frame", "get_frame(label='frame')", "PER", "Save the current RGB frame into the workspace frames/ directory when available and return safe frame metadata.", {"label": "Short label used in the saved frame filename."}, "dict with saved/path/shape/path_boundary", "workspace frame copy only", "L2 visual evidence", ["Does not move the simulator, embed image bytes in trace, or expose backend absolute paths in OpenHands mode."], "ThorEnv.last_event.frame"),
    PrimitiveCard("inspect_current_view", "inspect_current_view(label=None, remember=True)", "PER", "Capture the current RGB frame, return the current observation and visible objects, and optionally store them in visual memory.", {"label": "Optional memory/frame label.", "remember": "Whether to add visible objects to run-local visual memory."}, "dict with frame, observation, visible_objects, remembered_count, memory_count", "workspace frame copy + memory only", "L2 visual evidence", ["Does not move, search, path-find, or interact with objects.", "Only visible objects in the current frame are returned."], "ThorEnv.last_event.frame + visible metadata"),
    PrimitiveCard("detect_objects", "detect_objects(query=None)", "DET", "Return visible objects, optionally filtered by object type/name/objectId text.", {"query": "Optional object query."}, "list[dict]", "none", "L2 visible metadata", ["Visible objects only."], "visible metadata"),
    PrimitiveCard("remember_visible_objects", "remember_visible_objects(label=None, query=None)", "EVD", "Store currently visible objects in run-local visual memory, optionally filtered by query and tagged by label.", {"label": "Optional memory tag.", "query": "Optional visible-object filter."}, "dict with remembered_count, memory_count, objects", "memory only", "L2 visible metadata", ["Stores only objects visible at call time; does not reveal hidden scene graph or move the agent."], "visible metadata + harness memory"),
    PrimitiveCard("recall_visible_objects", "recall_visible_objects(query=None, label=None, limit=50)", "EVD", "Return objects previously stored in visual memory, sorted by latest sighting.", {"query": "Optional object type/name/objectId filter.", "label": "Optional memory tag.", "limit": "Maximum returned memories."}, "list[dict]", "none", "L2 remembered visible metadata", ["Memory can be stale; object may no longer be visible or reachable."], "harness visual memory"),
    PrimitiveCard("read_search_memory", "read_search_memory(query=None, label=None, limit=50)", "EVD", "Alias-style memory reader for search traces: return remembered visible objects filtered by query/label.", {"query": "Optional object type/name/objectId filter.", "label": "Optional memory tag.", "limit": "Maximum returned memories."}, "list[dict]", "none", "L2 remembered visible metadata", ["Reads only objects previously seen through perception/search primitives.", "Memory can be stale."], "harness visual memory"),
    PrimitiveCard("read_observed_spatial_map", "read_observed_spatial_map(query=None, limit=50)", "STATE", "Return an observed-only spatial memory summary: current pose, visited coarse cells, blocked moves, frontier hints, and seen object memory.", {"query": "Optional filter for seen objects.", "limit": "Maximum blocked moves / object memories returned."}, "dict with current_agent, visited_cells, blocked_moves, frontiers, seen_objects, boundary", "memory read only", "L2 observed metadata + L3 navigation memory", ["Only summarizes poses and objects observed through prior primitive calls.", "Does not expose hidden objects, full reachable map, target pose, shortest path, benchmark walkthrough data, masks, or low_actions.", "Frontiers are coarse heuristic neighbors of visited cells, not simulator-verified reachable positions."], "harness observed pose/object memory"),
    PrimitiveCard("scan_scene", "scan_scene(queries=None, rotations=4, include_tilts=True, remember=True)", "PER", "Perform a bounded in-place rotate/look scan, optionally remember seen objects, and return query hits.", {"queries": "String or list of object queries.", "rotations": "Number of left rotations, capped by harness.", "include_tilts": "Whether to look up/down during scan.", "remember": "Whether to store seen objects in visual memory."}, "dict with observations, query_hits, all_seen, memory_count", "bounded rotate/look native actions", "L2 visible metadata + L3 navigation", ["No path finding, no object interaction, no expert replay, and only objects visible during the scan are returned."], "observe + RotateLeft + LookUp/LookDown"),
    PrimitiveCard("search_scene", "search_scene(queries=None, rounds=3, scan_rotations=4, include_tilts=True, remember=True)", "PER", "Run several bounded scan_scene rounds, moving ahead slightly between rounds, and return aggregate query hits.", {"queries": "String or list of object queries.", "rounds": "Number of scan/move rounds, capped by harness.", "scan_rotations": "Rotate count per scan.", "include_tilts": "Whether each scan looks up/down.", "remember": "Whether to store seen objects in visual memory."}, "dict with scans, movement_events, query_hits, all_seen, memory_count", "bounded rotate/look/move native actions", "L2 visible metadata + L3 navigation", ["No object interaction, no path planning, no target manipulation, no expert replay; it may miss objects and may move into unhelpful poses."], "scan_scene + MoveAhead + RotateRight-if-blocked"),
    PrimitiveCard("explore_room", "explore_room(queries=None, step_budget=32, include_tilts=True, remember=True)", "PER", "Run a bounded generic room exploration pattern while recording visible-object memory and query hits.", {"queries": "String or list of object queries.", "step_budget": "Maximum native move/rotate/look actions, capped by harness.", "include_tilts": "Whether to periodically look up/down.", "remember": "Whether to store seen objects in visual memory."}, "dict with observations, movement_events, query_hits, all_seen, memory_count", "bounded move/rotate/look native actions", "L2 visible metadata + L3 navigation", ["No object interaction, no hidden map, no shortest-path planner, no target-specific route, and no expert replay; exploration can still miss objects."], "visible metadata + MoveAhead/RotateLeft/LookUp/LookDown"),
    PrimitiveCard("locate_object", "locate_object(query, aliases=None, support_queries=None, search_budget=36, include_tilts=True, open_containers=False)", "PER", "Bounded performance primitive for visual tasks: search for an object by aliases, use observed memory/support landmarks, approach a candidate, and reacquire it in the current view.", {"query": "Primary target query.", "aliases": "Optional target aliases such as ['DeskLamp', 'FloorLamp', 'Lamp'].", "support_queries": "Optional landmarks/containers/receptacles to search with the target.", "search_budget": "Internal native action budget, capped by harness.", "include_tilts": "Whether search scans look up/down.", "open_containers": "Whether to open a small number of currently visible matching containers during search."}, "dict with found, visible_now, current_object, best_candidate, candidates, events, spatial_memory", "bounded rotate/look/move/optional open native actions", "L2 visible metadata + L3 observed navigation", ["Does not use expert replay, hidden object ids, masks, full scene graph, shortest path, or target pose.", "Can still fail when the object is occluded, inside an unopened/unseen container, or unreachable.", "For manipulation, prefer the wrapper primitives below or use current_object only when visible_now is true."], "search_scene + explore_room + observed memory + approach_object"),
    PrimitiveCard("ground_object", "ground_object(query)", "DET", "Resolve a unique visible object by objectId, type, or name.", {"query": "Unique visible object query."}, "dict or error", "none", "L2 visible metadata", ["Ambiguous names fail and return visible candidates."], "visible metadata"),
    PrimitiveCard("query_object_state", "query_object_state(obj)", "STATE", "Return safe state fields for one visible or inventory object.", {"obj": "objectId, object dict, type, or name."}, "dict or error", "none", "L2 metadata", ["Does not expose full hidden scene graph."], "visible/inventory metadata"),
    PrimitiveCard("query_inventory", "query_inventory()", "STATE", "Return objects currently held by the agent.", {}, "list[dict]", "none", "L1", ["Only current inventory."], "metadata inventoryObjects"),
    PrimitiveCard("move_ahead", "move_ahead()", "NAV", "Move the agent one ALFRED/THOR step forward.", {}, "StepResult", "one native action", "L3", ["No path finding."], "MoveAhead"),
    PrimitiveCard("rotate", "rotate(direction)", "NAV", "Rotate the agent in place.", {"direction": "left or right."}, "StepResult", "one native action", "L3", ["No automatic target alignment."], "RotateLeft/RotateRight"),
    PrimitiveCard("look", "look(direction)", "NAV", "Tilt the camera.", {"direction": "up or down."}, "StepResult", "one native action", "L3", ["No object interaction."], "LookUp/LookDown"),
    PrimitiveCard("approach_object", "approach_object(obj, max_steps=3, stop_distance=1.25)", "NAV", "Coarsely turn and move toward a visible or remembered object position.", {"obj": "Visible or remembered object dict/objectId/type/name.", "max_steps": "Small bounded action budget.", "stop_distance": "Distance threshold."}, "dict with events, final_distance, final_observation", "bounded rotate/move native actions", "L2 remembered visible metadata + L3 navigation", ["No path finding, no obstacle map, no hidden object search, no object interaction; only works for visible or previously remembered objects."], "visible metadata/memory + RotateLeft/RotateRight + MoveAhead"),
    PrimitiveCard("open_object", "open_object(obj)", "HACT", "Open one visible openable object.", {"obj": "Visible object reference."}, "StepResult", "one native action", "L3", ["Fails if object is not visible/openable."], "OpenObject"),
    PrimitiveCard("close_object", "close_object(obj)", "HACT", "Close one visible openable object.", {"obj": "Visible object reference."}, "StepResult", "one native action", "L3", ["Fails if object is not visible/openable."], "CloseObject"),
    PrimitiveCard("pickup_object", "pickup_object(obj)", "HACT", "Pick up one visible pickupable object.", {"obj": "Visible object reference."}, "StepResult", "one native action", "L3", ["Fails if object is not visible/pickupable."], "PickupObject"),
    PrimitiveCard("put_object", "put_object(obj, receptacle)", "HACT", "Put the held object into/on a visible receptacle.", {"obj": "Held object reference.", "receptacle": "Visible receptacle reference."}, "StepResult", "one native action", "L3", ["No automatic pickup; object must already be held."], "PutObject"),
    PrimitiveCard("toggle_object", "toggle_object(obj, on=True)", "HACT", "Toggle a visible toggleable object on or off.", {"obj": "Visible object reference.", "on": "True for on, False for off."}, "StepResult", "one native action", "L3", ["Fails if object is not visible/toggleable."], "ToggleObjectOn/ToggleObjectOff"),
    PrimitiveCard("slice_object", "slice_object(obj)", "HACT", "Slice a visible sliceable object when holding a knife.", {"obj": "Visible sliceable object reference."}, "StepResult", "one native action", "L3", ["Does not auto-pickup knife or navigate."], "SliceObject"),
    PrimitiveCard("pickup_located_object", "pickup_located_object(query, aliases=None, support_queries=None, search_budget=36, open_containers=True)", "HACT", "Locate a target with bounded observed search, reacquire it in the current view, then attempt pickup_object.", {"query": "Primary pickup target query.", "aliases": "Optional target aliases.", "support_queries": "Likely supports/containers/receptacles to search alongside the target.", "search_budget": "Internal native action budget, capped by harness.", "open_containers": "Whether to open a small number of visible matching containers while locating."}, "dict with ok, locate, pickup, inventory, progress", "bounded search/navigation plus one PickupObject", "L2 visible metadata + L3 household action", ["Does not infer hidden target ids or use expert trajectories.", "It only picks up after current-view reacquisition; if target remains unseen, ok=false."], "locate_object + PickupObject"),
    PrimitiveCard("place_held_object", "place_held_object(receptacle_query, obj=None, aliases=None, support_queries=None, search_budget=36)", "HACT", "Use the current inventory, locate a receptacle with bounded observed search, then attempt put_object; if placement fails, move closer, reacquire, and retry once.", {"receptacle_query": "Primary receptacle query.", "obj": "Optional held object reference; defaults to first inventory object.", "aliases": "Optional receptacle aliases.", "support_queries": "Likely room landmarks to search alongside the receptacle.", "search_budget": "Internal native action budget, capped by harness."}, "dict with ok, held_object, receptacle, locate, put, put_attempts, retry, progress", "bounded search/navigation plus one or two PutObject attempts", "L2 visible metadata + L3 household action", ["Requires a held object.", "Does not choose the benchmark target from hidden state and does not solve task ordering automatically.", "The retry uses only observed receptacle memory/current-view reacquisition."], "query_inventory + locate_object + PutObject"),
    PrimitiveCard("toggle_located_object", "toggle_located_object(query, aliases=None, on=True, support_queries=None, search_budget=36)", "HACT", "Locate a toggleable target with bounded observed search, reacquire it in the current view, then attempt toggle_object.", {"query": "Primary toggle target query.", "aliases": "Optional aliases such as ['FloorLamp', 'DeskLamp', 'Lamp'].", "on": "True to turn on, False to turn off.", "support_queries": "Likely landmarks to search alongside the toggle target.", "search_budget": "Internal native action budget, capped by harness."}, "dict with ok, locate, toggle, progress", "bounded search/navigation plus one ToggleObjectOn/Off", "L2 visible metadata + L3 household action", ["Does not expose hidden light source ids or object poses.", "If no visible toggleable target is reacquired, ok=false."], "locate_object + ToggleObjectOn/Off"),
    PrimitiveCard("open_located_object", "open_located_object(query, aliases=None, support_queries=None, search_budget=24)", "HACT", "Locate a visible openable object such as a drawer/cabinet/fridge/microwave, then attempt open_object.", {"query": "Primary container/appliance query.", "aliases": "Optional aliases.", "support_queries": "Likely landmarks to search alongside the open target.", "search_budget": "Internal native action budget, capped by harness."}, "dict with ok, locate, open, progress", "bounded search/navigation plus one OpenObject", "L2 visible metadata + L3 household action", ["Does not search hidden container contents except through visible observations after opening.", "Not a task solver; use it as a subgoal primitive before searching for contained objects."], "locate_object + OpenObject"),
    PrimitiveCard("write_evidence", "write_evidence(key, value)", "EVD", "Store run-local notes for trace analysis.", {"key": "Evidence key.", "value": "JSON-serializable value."}, "dict", "none", "L1", ["Does not affect simulator state."], "harness memory"),
    PrimitiveCard("read_evidence", "read_evidence()", "EVD", "Read current run-local notes.", {}, "dict", "none", "L1", ["Current run only."], "harness memory"),
    PrimitiveCard("check_progress_public", "check_progress_public()", "VERIFY", "Return public progress, inventory, visible-object count, memory count, and step usage.", {}, "dict", "none", "L1 verifier summary", ["Does not reveal expert low_actions, masks, hidden target ids, or private trajectory fields."], "ThorEnv goal-condition checker + public observation summary"),
    PrimitiveCard("check_success", "check_success()", "VERIFY", "Return official ALFRED goal condition progress and success.", {}, "dict", "none", "L1 verifier summary", ["Does not reveal expert low_actions, masks, or hidden target object ids."], "ThorEnv.get_goal_conditions_met/get_goal_satisfied"),
]


def get_primitive_cards() -> list[dict[str, Any]]:
    return [card.to_dict() for card in PRIMITIVE_CARDS]


def render_primitive_cards_for_prompt() -> str:
    sections: list[str] = []
    for card in PRIMITIVE_CARDS:
        args = ", ".join(f"{name}: {desc}" for name, desc in card.arguments.items()) or "none"
        limits = " ".join(f"- {item}" for item in card.limitations)
        sections.append(
            "\n".join(
                [
                    f"{card.signature}",
                    f"  family: {card.canonical_family}",
                    f"  description: {card.description}",
                    f"  args: {args}",
                    f"  returns: {card.returns}",
                    f"  side_effect: {card.side_effect}",
                    f"  leakage_level: {card.leakage_level}",
                    f"  backend_source: {card.backend_source}",
                    f"  limitations: {limits}",
                ]
            )
        )
    return "\n\n".join(sections)
